apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
